version: '3.8'
services:
  updater:
    container_name: updater
    restart: always
    build:
      context: ./updater
    depends_on: 
      - uploader
    volumes:
      - ${CATASTRO_DATA}/update:/catastro
    command: ["python3", "-u", "/app/update.py"]

  uploader:
    container_name: uploader
    restart: always
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ${CATASTRO_DATA}:/data

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ${CATASTRO_DATA}:/data
