version: '3.8'
services:
  postgres:
    env_file:
    - .env.local

  uploader:
    volumes:
      - ${CATASTRO_DATA}:/data
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "--timeout", "600", "app:create_uploader()"]

  backend:
    env_file:
    - .env.local
    volumes:
      - ./backend:/app
      - ${CATASTRO_DATA}:/data
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "--timeout", "120", "app:create_app()"]
