version: '3.8'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgis/postgis:15-3.3
    env_file:
    - .env.local
    volumes:
      - ${CATASTRO_DATA}/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  updater:
    container_name: updater
    restart: always
    build:
      context: ./updater
    depends_on: 
      - uploader
    volumes:
      - ${CATASTRO_DATA}/update:/catastro
    command: ["python3", "-u", "/app/update.py"]
    labels:
      traefik.enable: "false"

  uploader:
    container_name: uploader
    restart: always
    build:
      context: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ${CATASTRO_DATA}:/data

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ${CATASTRO_DATA}:/data

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend

  traefik:
    container_name: traefik
    image: traefik:v3.0
    restart: always
