version: '3.7'
services:
  updater:
    container_name: updater
    restart: always
    build:
      context: ./updater
    depends_on: 
      - uploader
    command: ["python3", "-u", "/app/update.py"]

  uploader:
    container_name: uploader
    restart: always
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ${CATASTRO_DATA}:/data
    entrypoint: ["flask", "run", "--host=0.0.0.0"]
