"""Añade relación TaskLock -> TaskHistory

Revision ID: 03e2378f09f1
Revises: 8e372eb00ffa
Create Date: 2023-08-08 21:54:57.336146

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '03e2378f09f1'
down_revision = '8e372eb00ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_lock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'task_history', ['history_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_lock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('history_id')

    # ### end Alembic commands ###
