"""Añade validación a fixme

Revision ID: 1f75f7c5d54a
Revises: 8ede51e5bc72
Create Date: 2023-08-01 05:54:35.824661

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1f75f7c5d54a'
down_revision = '8ede51e5bc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixme', schema=None) as batch_op:
        batch_op.drop_column('validated')

    # ### end Alembic commands ###
