"""Campo bloqueo municipio

Revision ID: 308180d6cdab
Revises: 7de07efdd1a7
Create Date: 2023-07-12 08:35:13.308950

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '308180d6cdab'
down_revision = '7de07efdd1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_column('lock')

    # ### end Alembic commands ###
