"""Indexa tareas por código municipio y ref

Revision ID: 339c3295c7ac
Revises: b5d1761068a4
Create Date: 2023-05-22 08:41:03.254041

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '339c3295c7ac'
down_revision = 'b5d1761068a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_localid'), ['localid'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_muncode'), ['muncode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_muncode'))
        batch_op.drop_index(batch_op.f('ix_task_localid'))

    # ### end Alembic commands ###
