"""Elimina Municipality.Update

Revision ID: 43ad6c47cc94
Revises: 91a9ff02b763
Create Date: 2023-07-15 17:19:56.684522

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '43ad6c47cc94'
down_revision = '91a9ff02b763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.drop_index('idx_update_geom')
        batch_op.drop_index('ix_update_muncode')

    op.drop_table('update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('muncode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('uploaded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('childs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brothers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='update_pkey')
    )
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.create_index('ix_update_muncode', ['muncode'], unique=False)
        batch_op.create_index('idx_update_geom', ['geom'], unique=False)

    # ### end Alembic commands ###
