"""Columna validación de calles

Revision ID: 4621b9437de4
Revises: 825d0afb14ca
Create Date: 2023-06-21 09:18:53.517223

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4621b9437de4'
down_revision = '825d0afb14ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.drop_column('validated')

    # ### end Alembic commands ###
