"""Usuario

Revision ID: 503aed9402a2
Revises: 339c3295c7ac
Create Date: 2023-06-01 21:18:44.004632

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '503aed9402a2'
down_revision = '339c3295c7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('osm_id != import_id', name='ck_import_not_osm'),
    sa.ForeignKeyConstraint(['import_id'], ['osm_user.id'], ),
    sa.ForeignKeyConstraint(['osm_id'], ['osm_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('osm_user')
    # ### end Alembic commands ###
