"""Añade nivel mapeo

Revision ID: 612ef5c6be64
Revises: 705ecc9097cb
Create Date: 2023-08-06 20:33:20.945736

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '612ef5c6be64'
down_revision = '705ecc9097cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mapping_level')

    # ### end Alembic commands ###
