"""Campos para recuento de tareas

Revision ID: 6188f2e997ec
Revises: e490ed5406e2
Create Date: 2023-07-24 09:20:03.331955

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6188f2e997ec'
down_revision = 'e490ed5406e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.drop_column('task_count')

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_column('task_count')

    # ### end Alembic commands ###
