"""Migración inicial

Revision ID: 6c67f2f183c2
Revises: 
Create Date: 2023-04-24 14:52:45.664231

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '6c67f2f183c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipality_muncode'), ['muncode'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('localid', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('parts', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('codes_index', ['localid', 'muncode'], unique=False)
        #batch_op.create_index('idx_task_geom', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        #batch_op.drop_index('idx_task_geom', postgresql_using='gist')
        batch_op.drop_index('codes_index')

    op.drop_table('task')
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipality_muncode'))

    op.drop_table('municipality')
    # ### end Alembic commands ###
