"""Añade piscinas

Revision ID: 705ecc9097cb
Revises: 1f75f7c5d54a
Create Date: 2023-08-01 21:41:58.577104

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '705ecc9097cb'
down_revision = '1f75f7c5d54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pools', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('pools')

    # ### end Alembic commands ###
