"""Añade relación tareas municipio

Revision ID: 7de07efdd1a7
Revises: f8b55cfd0eb1
Create Date: 2023-07-11 20:26:19.692801

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '7de07efdd1a7'
down_revision = 'f8b55cfd0eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=True),
    sa.Column('childs', sa.String(), nullable=True),
    sa.Column('brothers', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update', schema=None) as batch_op:
        # batch_op.create_index('idx_update_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_update_muncode'), ['muncode'], unique=True)

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_index('ix_municipality_muncode')
        batch_op.create_index(batch_op.f('ix_municipality_muncode'), ['muncode'], unique=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('muncode',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key('task_muncode_fkey', 'municipality', ['muncode'], ['muncode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_muncode_fkey', type_='foreignkey')
        batch_op.alter_column('muncode',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipality_muncode'))
        batch_op.create_index('ix_municipality_muncode', ['muncode'], unique=False)

    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update_muncode'))
        # batch_op.drop_index('idx_update_geom', postgresql_using='gist')

    op.drop_table('update')
    # ### end Alembic commands ###
