"""Nombres de calles

Revision ID: 825d0afb14ca
Revises: adc52e6ddfc4
Create Date: 2023-06-14 16:55:38.176078

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '825d0afb14ca'
down_revision = 'adc52e6ddfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mun_code', sa.String(), nullable=True),
    sa.Column('cat_name', sa.String(), nullable=True),
    sa.Column('osm_name', sa.String(), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_street_cat_name'), ['cat_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_street_mun_code'), ['mun_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_street_osm_name'), ['osm_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_street_osm_name'))
        batch_op.drop_index(batch_op.f('ix_street_mun_code'))
        batch_op.drop_index(batch_op.f('ix_street_cat_name'))

    op.drop_table('street')
    # ### end Alembic commands ###
