"""Tablas para fixmes y actualizaciones

Revision ID: 88b934ea0fc6
Revises: 308180d6cdab
Create Date: 2023-07-15 07:41:24.537900

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '88b934ea0fc6'
down_revision = '308180d6cdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('municipality_update', schema=None) as batch_op:
        # batch_op.create_index('idx_municipality_update_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_municipality_update_muncode'), ['muncode'], unique=True)

    op.create_table('task_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('localid', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['muncode'], ['municipality_update.muncode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('task_update', schema=None) as batch_op:
    #     batch_op.create_index('idx_task_update_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('fixme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('src_date', sa.Date(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('update_id', sa.Integer(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['task_update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('fixme', schema=None) as batch_op:
    #     batch_op.create_index('idx_fixme_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('task_update_id_fkey', 'task_update', ['update_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_update_id_fkey', type_='foreignkey')
        batch_op.drop_column('update_id')

    # with op.batch_alter_table('fixme', schema=None) as batch_op:
    #     batch_op.drop_index('idx_fixme_geom', postgresql_using='gist')

    op.drop_table('fixme')
    # with op.batch_alter_table('task_update', schema=None) as batch_op:
    #     batch_op.drop_index('idx_task_update_geom', postgresql_using='gist')

    op.drop_table('task_update')
    with op.batch_alter_table('municipality_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipality_update_muncode'))
        # batch_op.drop_index('idx_municipality_update_geom', postgresql_using='gist')

    op.drop_table('municipality_update')
    # ### end Alembic commands ###
