"""Elimina relación fixme-task.update

Revision ID: 88c62a2ddb3d
Revises: 9ebb1356a133
Create Date: 2023-07-17 13:11:31.137743

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '88c62a2ddb3d'
down_revision = '9ebb1356a133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixme', schema=None) as batch_op:
        batch_op.drop_constraint('fixme_update_id_fkey', type_='foreignkey')
        batch_op.drop_column('update_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fixme_update_id_fkey', 'task_update', ['update_id'], ['id'])

    # ### end Alembic commands ###
