"""Restricción unicidad para cuentas de importación y osm

Revision ID: 8a8755ab2439
Revises: 9baf5b3298ca
Create Date: 2023-07-08 22:56:26.839531

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8a8755ab2439'
down_revision = '9baf5b3298ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['import_id'])
        batch_op.create_unique_constraint(None, ['osm_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
