"""Añade fecha creación a municipio

Revision ID: 8e372eb00ffa
Revises: b6c3a5af8b57
Create Date: 2023-08-07 22:47:04.207557

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8e372eb00ffa'
down_revision = 'b6c3a5af8b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
