"""Prueba para separar bloqueo de historial en calle

Revision ID: 8ea33011964c
Revises: b4a0d5a3776c
Create Date: 2023-06-30 08:26:50.517372

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8ea33011964c'
down_revision = 'b4a0d5a3776c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('street_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street_lock')
    # ### end Alembic commands ###
