"""Deshace añade centro

Revision ID: 8ede51e5bc72
Revises: dfbc00584fad
Create Date: 2023-07-31 08:11:01.876088

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '8ede51e5bc72'
down_revision = 'dfbc00584fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        #batch_op.drop_index('idx_municipality_centre')
        batch_op.drop_column('centre')

    with op.batch_alter_table('province', schema=None) as batch_op:
        #batch_op.drop_index('idx_province_centre')
        batch_op.drop_column('centre')

    with op.batch_alter_table('task', schema=None) as batch_op:
        #batch_op.drop_index('idx_task_centre')
        batch_op.drop_column('centre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
        #batch_op.create_index('idx_task_centre', ['centre'], unique=False)

    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
        #batch_op.create_index('idx_province_centre', ['centre'], unique=False)

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
        #batch_op.create_index('idx_municipality_centre', ['centre'], unique=False)

    # ### end Alembic commands ###
