"""Faltaba relacionar MunicipalityUpdate

Revision ID: 91a9ff02b763
Revises: 88b934ea0fc6
Create Date: 2023-07-15 16:27:23.525139

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '91a9ff02b763'
down_revision = '88b934ea0fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('municipality_update_id_fkey', 'municipality_update', ['update_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_constraint('municipality_update_id_fkey', type_='foreignkey')
        batch_op.drop_column('update_id')

    # ### end Alembic commands ###
