"""Faltaba para quitar relación municipios-tareas

Revision ID: 9ebb1356a133
Revises: 1d70c6e5593a
Create Date: 2023-07-17 10:44:39.771619

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9ebb1356a133'
down_revision = '1d70c6e5593a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_muncode_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_foreign_key('task_muncode_fkey', 'municipality', ['muncode'], ['muncode'])

    # ### end Alembic commands ###
