"""Añade imagen a usuario

Revision ID: a17557da87f5
Revises: bd17058f2eb4
Create Date: 2023-07-05 22:55:44.303954

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a17557da87f5'
down_revision = 'bd17058f2eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osm_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osm_user', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
