"""Provincias

Revision ID: adc52e6ddfc4
Revises: 34092e2fb9c2
Create Date: 2023-06-05 21:38:18.288231

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'adc52e6ddfc4'
down_revision = '34092e2fb9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('province', schema=None) as batch_op:
        # batch_op.create_index('idx_province_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_province_provcode'), ['provcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_province_provcode'))
        # batch_op.drop_index('idx_province_geom', postgresql_using='gist')

    op.drop_table('province')
    # ### end Alembic commands ###
