"""Translada mapping_level y date_registered de User a OsmUser

Revision ID: b3c1300b17d1
Revises: 03e2378f09f1
Create Date: 2023-08-25 22:42:48.222869

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b3c1300b17d1'
down_revision = '03e2378f09f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osm_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mapping_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_level', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('osm_user', schema=None) as batch_op:
        batch_op.drop_column('date_registered')
        batch_op.drop_column('mapping_level')

    # ### end Alembic commands ###
