"""Desdobla estado de tarea por edificios y direcciones

Revision ID: b4a0d5a3776c
Revises: 96a7478bc2a0
Create Date: 2023-06-29 08:56:32.306416

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b4a0d5a3776c'
down_revision = '96a7478bc2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bu_status', sa.Integer(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('bu_status')
        batch_op.drop_column('ad_status')

    # ### end Alembic commands ###
