"""Diferencia fixmes de edificios y direcciones

Revision ID: b5e5e3bd5600
Revises: 03e2378f09f1
Create Date: 2023-08-21 06:35:53.246470

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b5e5e3bd5600'
down_revision = '03e2378f09f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addresses', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('buildings', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixme', schema=None) as batch_op:
        batch_op.drop_column('buildings')
        batch_op.drop_column('addresses')

    # ### end Alembic commands ###
