"""Añade complejidad a Tarea

Revision ID: b690f93cc2d8
Revises: 4621b9437de4
Create Date: 2023-06-26 08:32:58.972775

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b690f93cc2d8'
down_revision = '4621b9437de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buildings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('addresses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('addresses')
        batch_op.drop_column('buildings')

    # ### end Alembic commands ###
