"""Indice compuesto TMTask

Revision ID: bdfacea0af03
Revises: b3c1300b17d1
Create Date: 2023-08-25 22:44:58.657012

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'bdfacea0af03'
down_revision = 'b3c1300b17d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('addresses', sa.Boolean(), nullable=True),
    sa.Column('buildings', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmtask',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['tmproject.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    # with op.batch_alter_table('tmtask', schema=None) as batch_op:
    #    batch_op.create_index('idx_tmtask_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('task_tmtask',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('tmproject_id', sa.Integer(), nullable=True),
    sa.Column('tmtask_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['tmproject_id', 'tmtask_id'], ['tmtask.project_id', 'tmtask.id'], name='tmtasks_fkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tmtask')
    #with op.batch_alter_table('tmtask', schema=None) as batch_op:
    #    batch_op.drop_index('idx_tmtask_geom', postgresql_using='gist')

    op.drop_table('tmtask')
    op.drop_table('tmproject')
    # ### end Alembic commands ###
