"""Añade municipio

Revision ID: d85fc6227385
Revises: 8ff47445fdd9
Create Date: 2023-04-22 08:36:08.859775

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd85fc6227385'
down_revision = '8ff47445fdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality',
    sa.Column('muncode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('muncode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipality')
    # ### end Alembic commands ###
