"""Añade tareas y proyectos del Gestor de Tareas

Revision ID: db82abdb14ab
Revises: 03e2378f09f1
Create Date: 2023-08-23 16:07:31.518221

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'db82abdb14ab'
down_revision = '03e2378f09f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('addresses', sa.Boolean(), nullable=True),
    sa.Column('buildings', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('muncode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['tmproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('tmtask', schema=None) as batch_op:
    #     batch_op.create_index('idx_tmtask_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('task_tmtask',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('tmtask_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['tmtask_id'], ['tmtask.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tmtask')
    # with op.batch_alter_table('tmtask', schema=None) as batch_op:
    #     batch_op.drop_index('idx_tmtask_geom', postgresql_using='gist')

    op.drop_table('tmtask')
    op.drop_table('tmproject')
    # ### end Alembic commands ###
