"""Añade centro a tareas, municipios y provincias

Revision ID: dfbc00584fad
Revises: 6188f2e997ec
Create Date: 2023-07-28 16:24:26.551690

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'dfbc00584fad'
down_revision = '6188f2e997ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        #batch_op.create_index('idx_municipality_centre', ['centre'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        #batch_op.create_index('idx_province_centre', ['centre'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        #batch_op.create_index('idx_task_centre', ['centre'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        #batch_op.drop_index('idx_task_centre', postgresql_using='gist')
        batch_op.drop_column('centre')

    with op.batch_alter_table('province', schema=None) as batch_op:
        #batch_op.drop_index('idx_province_centre', postgresql_using='gist')
        batch_op.drop_column('centre')

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        #batch_op.drop_index('idx_municipality_centre', postgresql_using='gist')
        batch_op.drop_column('centre')

    # ### end Alembic commands ###
