"""Elimina relación task.update-municipality.update

Revision ID: e490ed5406e2
Revises: 88c62a2ddb3d
Create Date: 2023-07-17 17:14:55.584030

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e490ed5406e2'
down_revision = '88c62a2ddb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_update', schema=None) as batch_op:
        batch_op.drop_constraint('task_update_muncode_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_update', schema=None) as batch_op:
        batch_op.create_foreign_key('task_update_muncode_fkey', 'municipality_update', ['muncode'], ['muncode'])

    # ### end Alembic commands ###
