"""Bloqueo e historial de tareas

Revision ID: e8338fc6e522
Revises: 8ea33011964c
Create Date: 2023-07-01 21:34:38.069994

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e8338fc6e522'
down_revision = '8ea33011964c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buildings', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('addresses', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_column('addresses')
        batch_op.drop_column('buildings')

    # ### end Alembic commands ###
