"""Quitar relación municipios-tareas, municipality.date -> src_date

Revision ID: fdc2b4397d82
Revises: 43ad6c47cc94
Create Date: 2023-07-16 21:23:07.963737

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fdc2b4397d82'
down_revision = '43ad6c47cc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_date', sa.Date(), nullable=False))
        batch_op.drop_column('lock')
        batch_op.drop_column('date')

    with op.batch_alter_table('municipality_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_date', sa.Date(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('src_date')

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lock', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('src_date')

    # ### end Alembic commands ###
